replicaCount: 1

image:
  repository: identity-provider
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 80

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Development"
  - name: ConnectionStrings__DefaultConnection
    value: "Host=postgresql;Database=identity;Username=myuser;Password=mypassword"
  - name: Kafka__BootstrapServers
    value: "kafka-kafka:9092"
  - name: ServiceName
    value: "identity-provider"

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: false
  host: ticket-booking-system.local
  path: /identity-provider
  tlsSecret: ticket-booking-system-tls