ingressName: ticket-booking-system-ingress
host: ticket-booking-system.local
services:
  - path: /simple-concert-service
    serviceName: simple-concert-service-microservice-generic
    servicePort: 80
  - path: /simple-cinema-service
    serviceName: simple-cinema-service-microservice-generic
    servicePort: 80
  - path: /identity-provider
    serviceName: identity-provider-microservice-generic
    servicePort: 80
  - path: /concert-aggregator
    serviceName: concert-aggregator-microservice-generic
    servicePort: 80
  - path: /gateway
    serviceName: gateway-microservice-generic
    servicePort: 80
  - path: /libretranslate
    serviceName: libretranslate
    servicePort: 80